services:
  redis:
    image: redis:latest
    container_name: filepizza-redis
    restart: unless-stopped
    networks:
      - filepizza
    volumes:
      - ./redis_data:/data
  coturn:
    image: coturn/coturn
    container_name: filepizza-coturn
    restart: unless-stopped
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - 60000-60128:60000-60128/udp
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
    command: -n --log-file=stdout --redis-userdb="ip=redis connect_timeout=30" --min-port=60000 --max-port=60128
    networks:
      - filepizza
  filepizza:
    build: .
    image: do1e/filepizza:latest
    container_name: filepizza
    restart: unless-stopped
    ports:
      - 127.0.0.1:18705:18705
    environment:
      - PORT=18705
      - REDIS_URL=redis://redis:6379
      - COTURN_ENABLED=true
    networks:
      - filepizza
    depends_on:
      - redis

networks:
  filepizza:
    driver: bridge
